/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "suma.h"

bool_t
xdr_sumandos (XDR *xdrs, sumandos *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->sumando1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sumando2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sumando3))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sumando4))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->sumando1);
			IXDR_PUT_LONG(buf, objp->sumando2);
			IXDR_PUT_LONG(buf, objp->sumando3);
			IXDR_PUT_LONG(buf, objp->sumando4);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->sumando1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sumando2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sumando3))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sumando4))
				 return FALSE;
		} else {
			objp->sumando1 = IXDR_GET_LONG(buf);
			objp->sumando2 = IXDR_GET_LONG(buf);
			objp->sumando3 = IXDR_GET_LONG(buf);
			objp->sumando4 = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->sumando1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sumando2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sumando3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sumando4))
		 return FALSE;
	return TRUE;
}
