/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"
#include <math.h>

int * suma_1_svc(sumandos *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	switch(argp->op){
		case 1: result=argp->sumando1 + argp->sumando2;
		break;
		case 2: result=argp->sumando1 - argp->sumando2;
		break;
		case 3: result=argp->sumando1 / argp->sumando2;
		break;
		case 4: result=argp->sumando1 * argp->sumando2;
		break;
		case 5: result=(int)(sin(argp->sumando1));
		break;
		case 6: result=(int)(cos(argp->sumando1));
		break;
		case 7: result=(int)(tan(argp->sumando1));
		break;
		default: break;
	
	}
	return &result;
}
